// Data kalimat bahasa Arab dan terjemahannya
const sentences = [
    { id: 1, indo: "Jangan tidur di shaff depan", arab: "لَا تَنَمْ فِي الصَّفِّ الْأَمَامِيِّ" },
    { id: 2, indo: "Kelas tiga di shaff pertama", arab: "ٱلْمَرْحَلَةُ ٱلثَّالِثَةُ فِي ٱلصَّفِّ ٱلْأَوَّلِ" },
    { id: 3, indo: "Jangan berdiri di depan pintu", arab: "لَا تَقِفْ أَمَامَ الْبَابِ" },
    { id: 4, indo: "Jangan duduk di atas meja", arab: "لَا تَجْلِسْ عَلَى الْمَكْتَبِ" },
    { id: 5, indo: "Jangan makan di dalam kelas", arab: "لَا تَأْكُلْ فِي الْفَصْلِ" },
    { id: 6, indo: "Jangan minum sambil berdiri", arab: "لَا تَشْرَبْ وَاقِفًا" },
    { id: 7, indo: "Jangan berlari di koridor", arab: "لَا تَجْرِ فِي الْمَمَرِّ" },
    { id: 8, indo: "Jangan berteriak di perpustakaan", arab: "لَا تَصْرُخْ فِي الْمَكْتَبَةِ" },
    { id: 9, indo: "Jangan buang sampah sembarangan", arab: "لَا تَرْمِ النُّفَايَاتِ عَشْوَائِيًّا" },
    { id: 10, indo: "Jangan terlambat masuk kelas", arab: "لَا تَتَأَخَّرْ عَنِ الْفَصْلِ" },
    { id: 11, indo: "Buka bukumu halaman sepuluh", arab: "اِفْتَحْ كِتَابَكَ صَفْحَةَ عَشَرَةٍ" },
    { id: 12, indo: "Tulislah namamu di atas kertas", arab: "اُكْتُبْ اسْمَكَ عَلَى الْوَرَقَةِ" },
    { id: 13, indo: "Bacalah dengan suara keras", arab: "اِقْرَأْ بِصَوْتٍ عَالٍ" },
    { id: 14, indo: "Jawablah pertanyaan-pertanyaan ini", arab: "أَجِبْ عَنْ هَذِهِ الْأَسْئِلَةِ" },
    { id: 15, indo: "Perhatikan penjelasan guru", arab: "اِنْتَبِهْ إِلَى شَرْحِ الْمُعَلِّمِ" },
    { id: 16, indo: "Ulangi setelah saya", arab: "كَرِّرْ بَعْدِي" },
    { id: 17, indo: "Kerjakan latihan ini", arab: "أَدِّ هَذَا التَّمْرِينَ" },
    { id: 18, indo: "Hafalkan ayat-ayat ini", arab: "اِحْفَظْ هَذِهِ الْآيَاتِ" },
    { id: 19, indo: "Bersihkan papan tulis", arab: "نَظِّفِ السَّبُّورَةَ" },
    { id: 20, indo: "Matikan lampu sebelum keluar", arab: "أَطْفِئِ الْمِصْبَاحَ قَبْلَ الْخُرُوجِ" },
    { id: 21, indo: "Saya suka membaca buku", arab: "أُحِبُّ قِرَاءَةَ الْكُتُبِ" },
    { id: 22, indo: "Dia pergi ke sekolah setiap hari", arab: "يَذْهَبُ إِلَى الْمَدْرَسَةِ كُلَّ يَوْمٍ" },
    { id: 23, indo: "Mereka belajar bahasa Arab", arab: "هُمْ يَدْرُسُونَ اللُّغَةَ الْعَرَبِيَّةَ" },
    { id: 24, indo: "Kami menulis pelajaran", arab: "نَكْتُبُ الدَّرْسَ" },
    { id: 25, indo: "Dia (pr) membaca Al-Quran", arab: "هِيَ تَقْرَأُ الْقُرْآنَ" },
    { id: 26, indo: "Guru mengajar murid-murid", arab: "الْمُعَلِّمُ يُعَلِّمُ الطُّلَّابَ" },
    { id: 27, indo: "Murid-murid memahami pelajaran", arab: "الطُّلَّابُ يَفْهَمُونَ الدَّرْسَ" },
    { id: 28, indo: "Saya makan di kantin", arab: "آكُلُ فِي الْمَقْصَفِ" },
    { id: 29, indo: "Kami bermain di halaman", arab: "نَلْعَبُ فِي السَّاحَةِ" },
    { id: 30, indo: "Dia (lk) tidur di kamar", arab: "هُوَ يَنَامُ فِي الْغُرْفَةِ" },
    { id: 31, indo: "Ini buku baru", arab: "هَذَا كِتَابٌ جَدِيدٌ" },
    { id: 32, indo: "Itu tas besar", arab: "تِلْكَ حَقِيبَةٌ كَبِيرَةٌ" },
    { id: 33, indo: "Rumah itu besar", arab: "الْبَيْتُ كَبِيرٌ" },
    { id: 34, indo: "Sekolah ini bersih", arab: "هَذِهِ الْمَدْرَسَةُ نَظِيفَةٌ" },
    { id: 35, indo: "Mobil itu cepat", arab: "تِلْكَ السَّيَّارَةُ سَرِيعَةٌ" },
    { id: 36, indo: "Pintu itu terbuka", arab: "الْبَابُ مَفْتُوحٌ" },
    { id: 37, indo: "Jendela itu tertutup", arab: "النَّافِذَةُ مُغْلَقَةٌ" },
    { id: 38, indo: "Buah itu segar", arab: "الْفَاكِهَةُ طَازَجَةٌ" },
    { id: 39, indo: "Air itu dingin", arab: "الْمَاءُ بَارِدٌ" },
    { id: 40, indo: "Cuaca hari ini panas", arab: "الْجَوُّ الْيَوْمَ حَارٌّ" },
    { id: 41, indo: "Berapa jam kamu belajar setiap hari?", arab: "كَمْ سَاعَةً تَدْرُسُ كُلَّ يَوْمٍ؟" },
    { id: 42, indo: "Di mana kamu tinggal?", arab: "أَيْنَ تَسْكُنُ؟" },
    { id: 43, indo: "Kapan kamu bangun tidur?", arab: "مَتَى تَسْتَيْقِظُ مِنَ النَّوْمِ؟" },
    { id: 44, indo: "Mengapa kamu terlambat?", arab: "لِمَاذَا تَأَخَّرْتَ؟" },
    { id: 45, indo: "Bagaimana kabarmu hari ini?", arab: "كَيْفَ حَالُكَ الْيَوْمَ؟" },
    { id: 46, indo: "Siapa gurumu?", arab: "مَنْ مُعَلِّمُكَ؟" }
];