// Data kalimat bahasa Arab dan terjemahannya
const sentences = [
    { id: 1, indo: "Jangan tidur di shaff depan", arab: "لَا تَنَمْ فِي الصَّفِّ الْأَمَامِيِّ" },
    { id: 2, indo: "Kelas tiga di shaff pertama", arab: "ٱلْمَرْحَلَةُ ٱلثَّالِثَةُ فِي ٱلصَّفِّ ٱلْأَوَّلِ" },
    { id: 3, indo: "Jangan main lari-lari", arab: "لَا تَلْعَبْ بِالْجَرْيِ" },
    { id: 4, indo: "Ambilkan Quranku dong", arab: "هَاتِ لِي قُرْآنِي" },
    { id: 5, indo: "Sudah shalat sunnah belum?", arab: "هَلْ صَلَّيْتَ السُّنَّةَ؟" },
    { id: 6, indo: "Jangan berisik di masjid", arab: "لَا تُزْعِجْ فِي الْمَسْجِدِ" },
    { id: 7, indo: "Jangan salto, nanti roboh", arab: "لَا تَقُمْ بِالسَّلْتُو، قَدْ يَسْقُطَ" },
    { id: 8, indo: "Kerja bagus", arab: "عَمَلٌ جَيِّدٌ" },
    { id: 9, indo: "Ada buaya", arab: "هُنَاكَ تِمْسَاحٌ!" },
    { id: 10, indo: "Ada duit kah?", arab: "هَلْ عِنْدَكَ فُلُوس؟" },
    { id: 11, indo: "Izin dulu", arab: "اسْتَأْذِنْ أَوَّلًا" },
    { id: 12, indo: "Pergi ke tambang yuk", arab: "هَيَّا نَذْهَبْ إِلَى الْمَنْجَمِ" },
    { id: 13, indo: "Tolong ambilkan parfum", arab: "مِنْ فَضْلِكَ، أَحْضِرْ لِيَ الْعِطْرَ" },
    { id: 14, indo: "Ngelunjak kali kau", arab: "أَنْتَ وَقِحٌ جِدًّا!" },
    { id: 15, indo: "Tolong belikan es", arab: "مِنْ فَضْلِكَ، اشْتَرِ لِيَ ثَلْجًا" },
    { id: 16, indo: "Bersihin, kotor nih", arab: "نَظِّفْ، إِنَّهُ مُتَّسِخٌ" },
    { id: 17, indo: "Sapu lantainya", arab: "اكْنُسِ الْأَرْضَ" },
    { id: 18, indo: "Mana kopiahku?", arab: "أَيْنَ قَلَنْسُوَتِي؟" },
    { id: 19, indo: "Nyalakan kipasnya", arab: "شَغِّلِ الْمِرْوَحَةَ" },
    { id: 20, indo: "Wih, ngerinya pang", arab: "وَاه! إِنَّهُ مُخِيفٌ جِدًّا!" },
    { id: 21, indo: "Nggak ngotak bah", arab: "هٰذَا غَيْرُ مَعْقُولٍ!" },
    { id: 22, indo: "Jangan shake es, takut tumpah", arab: "لَا تَهُزَّ الثَّلْجَ، قَدْ يَنْسَكِبَ" },
    { id: 23, indo: "Nggak boleh mainan di kamar mandi", arab: "لَا يَجُوزُ اللَّعِبُ فِي الْحَمَّامِ" },
    { id: 24, indo: "Kamu sakit kah?", arab: "هَلْ أَنْتَ مَرِيضٌ؟" },
    { id: 25, indo: "Santai dong mukanya", arab: "هَدِّئْ وَجْهَكَ قَلِيلًا" },
    { id: 26, indo: "Berapa menit lagi adzan?", arab: "كَمْ بَقِيَ عَلَى الْأَذَانِ؟" },
    { id: 27, indo: "Wudhu sebelum shalat!", arab: "تَوَضَّأْ قَبْلَ الصَّلَاةِ!" },
    { id: 28, indo: "Sana jauh-jauh", arab: "ابْتَعِدْ!" },
    { id: 29, indo: "Mana tongkat mimbar", arab: "أَيْنَ عَصَا الْمِنْبَرِ؟" },
    { id: 30, indo: "Mic mati", arab: "الْمِيكْرُوفُونُ مَطْفَأٌ" },
    { id: 31, indo: "Sajadah rusak", arab: "السَّجَّادَةُ مُمَزَّقَةٌ" },
    { id: 32, indo: "Vacum ambal", arab: "نَظِّفِ الْفُرُشَ بِالْمِكْنَسَةِ الْكَهْرَبَائِيَّةِ" },
    { id: 33, indo: "Piket masjid", arab: "نَوْبَةُ النَّظَافَةِ فِي الْمَسْجِدِ" },
    { id: 34, indo: "Hijab jatuh", arab: "السِّتَارَةُ سَقَطَتْ" },
    { id: 35, indo: "Hayooo mimbar rusak", arab: "هَيَّهْ! الْمِنْبَرُ مَكْسُورٌ!" },
    { id: 36, indo: "Hayooo sajadah robek", arab: "هَيَّهْ! السَّجَّادَةُ مُمَزَّقَةٌ!" },
    { id: 37, indo: "Pakai sarung", arab: "ٱلْبَسِ ٱلْإِزَارَ" },
    { id: 38, indo: "Rapiin Quran", arab: "رَتِّبِ الْقُرْآنَ" },
    { id: 39, indo: "Nggak boleh ngomong kasar", arab: "لَا تَتَكَلَّمْ بِكَلِمَاتٍ بَذِيئَةٍ" },
    { id: 40, indo: "Eh, aku mau cerita sama kalian", arab: "أَهْ، أُرِيدُ أَنْ أُحَدِّثَكُمْ بِقِصَّةٍ" },
    { id: 41, indo: "Ambilkan minum nah", arab: "أَحْضِرْ لِي شَرَابًا، نَحْ" },
    { id: 42, indo: "Jangan lari-lari", arab: "لَا تَجْرِ!" },
    { id: 43, indo: "Isi shaffnya", arab: "أَتْمِمُوا الصَّفَّ" },
    { id: 44, indo: "Siapa yang adzan?", arab: "مَنْ يُؤَذِّنُ؟" },
    { id: 45, indo: "Jangan freestyle di masjid. Nanti roboh", arab: "لَا تَقُمْ بِالْحَرَكَاتِ الْحُرَّةِ فِي الْمَسْجِدِ، قَدْ يَسْقُطَ" }
];